### ISSUE TITLE
Migrate from jcenter

### ISSUE THREAD

**Issue by Dansoftowner** [tom91136/GestureFX#7]
Hi @tom91136! 

First of all, thanks for this awesome library, it's really useful!

GestureFX is distributed on `jcenter`. The problem is that JFrog [announced that they will be shutting down Bintray and JCenter](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), so you should migrate to a different alternative.

Now I use [JitPack](https://jitpack.io/#tom91136/GestureFX/gesturefx-parent-0.6.0) for downloading your library:
```groovy
repositories {
	...
	maven { url 'https://jitpack.io' }
}

dependencies {
	 implementation 'com.github.tom91136.GestureFX:gesturefx:gesturefx-parent-0.6.0'
}

```

Best regards

**Comment by tom91136** [comment]
0.7.1 is now released on Maven Central
